openapi: 3.0.3
info:
  title: Movie Reservation System
  version: 0.0.1
servers:
  - url: /v1
tags:
  - name: health
    description: Related to server's health
paths:
  /healthcheck:
    get:
      tags:
        - health
      summary: Get the server status
      operationId: getHealth
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthcheckResponse'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - message
        - timestamp
        - requestId
      properties:
        message:
          type: string
          description: A human-readable description of the error.
          example: "Resource not found"
        timestamp:
          type: string
          format: date-time
          description: ISO 8601 timestamp of when the error occurred.
          example: "2024-12-01T14:32:28Z"
        requestId:
          type: string
          description: A unique identifier for the request to help with tracing errors.
          example: "abc123xyz789"
    ValidationErrorResponse:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
        - type: object
          required:
            - validationErrors
          properties:
            validationErrors:
              type: array
              description: A list of validation errors that occurred.
              items:
                type: object
                required:
                  - field
                  - issue
                properties:
                  field:
                    type: string
                    description: The name of the invalid field.
                    example: "email"
                  issue:
                    type: string
                    description: A description of what is wrong with the field.
                    example: "Email is not in a valid format"
    HealthcheckResponse:
      type: object
      required:
        - status
        - systemInfo
      properties:
        status:
          type: string
          description: "The current status of the system."
        systemInfo:
          $ref: "#/components/schemas/SystemInfo"
          description: "Detailed information about the system, including environment and version."
    SystemInfo:
      type: object
      required:
        - environment
        - version
      properties:
        environment:
          type: string
          description: "The deployment environment of the system, e.g., 'prod', 'staging', or 'dev'."
        version:
          type: string
          description: "The current version of the application or API."
