// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message A human-readable description of the error.
	Message string `json:"message"`

	// RequestId A unique identifier for the request to help with tracing errors.
	RequestId string `json:"requestId"`

	// Timestamp ISO 8601 timestamp of when the error occurred.
	Timestamp time.Time `json:"timestamp"`
}

// HealthcheckResponse defines model for HealthcheckResponse.
type HealthcheckResponse struct {
	// Status The current status of the system.
	Status     string     `json:"status"`
	SystemInfo SystemInfo `json:"systemInfo"`
}

// SystemInfo defines model for SystemInfo.
type SystemInfo struct {
	// Environment The deployment environment of the system, e.g., 'prod', 'staging', or 'dev'.
	Environment string `json:"environment"`

	// Version The current version of the application or API.
	Version string `json:"version"`
}
